language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
before_script:
  - npm install -g bower polymer-cli
  - bower install
script:
  - xvfb-run polymer test 
before_deploy:
  - xvfb-run polymer build
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: navidad-con-firebase
    token: $FIREBASE_TOKEN
    on:
      branch: master