language: node_js
sudo: required
dist: trusty
node_js:
  - '6'
cache:
  directories:
    - node_modules
branches:
  except:
    - /^v\d/
install:
  - npm install
  - npm install -g bower
  - bower install
script:
  - npm test
before_deploy:
  - npm run build
deploy:
  - provider: firebase
    edge: true
    skip_cleanup: true
    project: navidad-con-firebase
    token: $FIREBASE_TOKEN
    on:
      branch: master
